### ISSUE TITLE
Add HTTP status codes from RFC 6585

### ISSUE THREAD

**Issue by asilentdreamer** [grzhan/HttpStatusCodePowerToys#1]
[RFC 6585](https://datatracker.ietf.org/doc/html/rfc6585) specifies some additional http status codes which I believe could be added.

| **Code** | **Reason Phrase**               | **Description**                                                                         | **Defined In**                                                      |
| -------- | ------------------------------- | --------------------------------------------------------------------------------------- | ------------------------------------------------------------------- |
| 428      | Precondition Required           | The origin server requires the request to be conditional.                               | [RFC 6585, Section 3](http://tools.ietf.org/html/rfc6585#section-3) |
| 429      | Too Many Requests               | The user has sent too many requests in a given amount of time (rate limiting).          | [RFC 6585, Section 4](http://tools.ietf.org/html/rfc6585#section-4) |
| 431      | Request Header Fields Too Large | The server is unwilling to process the request because its header fields are too large. | [RFC 6585, Section 5](http://tools.ietf.org/html/rfc6585#section-5) |
| 511      | Network Authentication Required | The client needs to authenticate to gain network access.                                | [RFC 6585, Section 6](http://tools.ietf.org/html/rfc6585#section-6) |

**Comment by grzhan** [comment]
I will add these HTTP status codes within the next two days, thank you!

**Comment by grzhan** [comment]
@asilentdreamer I just added these HTTP status codes to the plugin and released version 0.1.1. You can download this version and check if the issue still exists.

**Comment by asilentdreamer** [comment]
It works as expected. Thanks for implementing this so quickly.
Closing this issue since its resolved.
